[2024-09-26T16:30:48.786+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-26T16:30:48.798+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Amazon_Book_Data.insert_book_data scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-26T16:30:48.804+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Amazon_Book_Data.insert_book_data scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-26T16:30:48.805+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-26T16:30:48.824+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-09-24 00:00:00+00:00
[2024-09-26T16:30:48.831+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1550) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-26T16:30:48.832+0000] {standard_task_runner.py:72} INFO - Started process 1555 to run task
[2024-09-26T16:30:48.833+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Amazon_Book_Data', 'insert_book_data', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/amazon_books.py', '--cfg-path', '/tmp/tmpg8jwql8_']
[2024-09-26T16:30:48.834+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask insert_book_data
[2024-09-26T16:30:48.874+0000] {task_command.py:467} INFO - Running <TaskInstance: Amazon_Book_Data.insert_book_data scheduled__2024-09-24T00:00:00+00:00 [running]> on host f04706ee9217
[2024-09-26T16:30:48.951+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Amazon_Book_Data' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-26T16:30:48.954+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-26T16:30:48.955+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-26T16:30:48.955+0000] {logging_mixin.py:190} INFO - Current task name:insert_book_data state:running start_date:2024-09-26 16:30:48.799201+00:00
[2024-09-26T16:30:48.955+0000] {logging_mixin.py:190} INFO - Dag name:Amazon_Book_Data and current dag run status:running
[2024-09-26T16:30:48.956+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-26T16:30:48.964+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/amazon_books.py", line 74, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-09-26T16:30:48.980+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-26T16:30:48.981+0000] {logging_mixin.py:190} INFO - Task start:2024-09-26 16:30:48.799201+00:00 end:2024-09-26 16:30:48.979410+00:00 duration:0.180209
[2024-09-26T16:30:48.982+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_book_data> dag:<DAG: Amazon_Book_Data> dagrun:<DagRun Amazon_Book_Data @ 2024-09-24 00:00:00+00:00: scheduled__2024-09-24T00:00:00+00:00, state:running, queued_at: 2024-09-26 16:30:40.605806+00:00. externally triggered: False>
[2024-09-26T16:30:48.982+0000] {logging_mixin.py:190} INFO - Failure caused by No book data found
[2024-09-26T16:30:48.983+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Amazon_Book_Data, task_id=insert_book_data, run_id=scheduled__2024-09-24T00:00:00+00:00, execution_date=20240924T000000, start_date=20240926T163048, end_date=20240926T163048
[2024-09-26T16:30:48.996+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-26T16:30:48.997+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 48 for task insert_book_data (No book data found; 1555)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/amazon_books.py", line 74, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-09-26T16:30:49.030+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-26T16:30:49.046+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-26T16:30:49.047+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-26T16:31:49.296+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-26T16:31:49.309+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Amazon_Book_Data.insert_book_data scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-26T16:31:49.316+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Amazon_Book_Data.insert_book_data scheduled__2024-09-24T00:00:00+00:00 [queued]>
[2024-09-26T16:31:49.316+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-26T16:31:49.326+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-09-24 00:00:00+00:00
[2024-09-26T16:31:49.331+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1588) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-26T16:31:49.333+0000] {standard_task_runner.py:72} INFO - Started process 1593 to run task
[2024-09-26T16:31:49.333+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Amazon_Book_Data', 'insert_book_data', 'scheduled__2024-09-24T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/amazon_books.py', '--cfg-path', '/tmp/tmpgdss3w5f']
[2024-09-26T16:31:49.335+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask insert_book_data
[2024-09-26T16:31:49.380+0000] {task_command.py:467} INFO - Running <TaskInstance: Amazon_Book_Data.insert_book_data scheduled__2024-09-24T00:00:00+00:00 [running]> on host f04706ee9217
[2024-09-26T16:31:49.441+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Amazon_Book_Data' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-24T00:00:00+00:00'
[2024-09-26T16:31:49.442+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-26T16:31:49.442+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-26T16:31:49.443+0000] {logging_mixin.py:190} INFO - Current task name:insert_book_data state:running start_date:2024-09-26 16:31:49.310289+00:00
[2024-09-26T16:31:49.443+0000] {logging_mixin.py:190} INFO - Dag name:Amazon_Book_Data and current dag run status:running
[2024-09-26T16:31:49.444+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-26T16:31:49.451+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/amazon_books.py", line 74, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-09-26T16:31:49.463+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-26T16:31:49.463+0000] {logging_mixin.py:190} INFO - Task start:2024-09-26 16:31:49.310289+00:00 end:2024-09-26 16:31:49.462610+00:00 duration:0.152321
[2024-09-26T16:31:49.464+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): insert_book_data> dag:<DAG: Amazon_Book_Data> dagrun:<DagRun Amazon_Book_Data @ 2024-09-24 00:00:00+00:00: scheduled__2024-09-24T00:00:00+00:00, state:running, queued_at: 2024-09-26 16:31:41.176778+00:00. externally triggered: False>
[2024-09-26T16:31:49.464+0000] {logging_mixin.py:190} INFO - Failure caused by No book data found
[2024-09-26T16:31:49.464+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Amazon_Book_Data, task_id=insert_book_data, run_id=scheduled__2024-09-24T00:00:00+00:00, execution_date=20240924T000000, start_date=20240926T163149, end_date=20240926T163149
[2024-09-26T16:31:49.474+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-26T16:31:49.475+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 54 for task insert_book_data (No book data found; 1593)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/amazon_books.py", line 74, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-09-26T16:31:49.508+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-26T16:31:49.519+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-26T16:31:49.520+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
