[2024-09-26T16:19:14.444+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-26T16:19:14.667+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Amazon_Book_Data.Fetch_Books_Data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-09-26T16:19:14.676+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Amazon_Book_Data.Fetch_Books_Data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-09-26T16:19:14.677+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-26T16:19:14.693+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): Fetch_Books_Data> on 2024-06-25 00:00:00+00:00
[2024-09-26T16:19:15.162+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1258) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-26T16:19:15.164+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Amazon_Book_Data', 'Fetch_Books_Data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/amazon_books.py', '--cfg-path', '/tmp/tmpd8q4ou7e']
[2024-09-26T16:19:15.176+0000] {standard_task_runner.py:72} INFO - Started process 1282 to run task
[2024-09-26T16:19:15.192+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask Fetch_Books_Data
[2024-09-26T16:19:16.895+0000] {task_command.py:467} INFO - Running <TaskInstance: Amazon_Book_Data.Fetch_Books_Data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f04706ee9217
[2024-09-26T16:19:21.032+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Amazon_Book_Data' AIRFLOW_CTX_TASK_ID='Fetch_Books_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-09-26T16:19:21.061+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-26T16:19:21.062+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-26T16:19:21.062+0000] {logging_mixin.py:190} INFO - Current task name:Fetch_Books_Data state:running start_date:2024-09-26 16:19:14.668397+00:00
[2024-09-26T16:19:21.063+0000] {logging_mixin.py:190} INFO - Dag name:Amazon_Book_Data and current dag run status:running
[2024-09-26T16:19:21.063+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-26T16:19:25.240+0000] {logging_mixin.py:190} INFO - Able to reach the site, scrapping data...
[2024-09-26T16:19:25.844+0000] {logging_mixin.py:190} INFO - The webpage has been scrapped for data...
[2024-09-26T16:19:25.866+0000] {logging_mixin.py:190} INFO - Books data has been scrapped from the website succesfully !!!
[2024-09-26T16:19:25.909+0000] {logging_mixin.py:190} INFO - Number of books scrapped :  50
[2024-09-26T16:19:25.909+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/amazon_books.py", line 68, in fetch_books_data
    ti.xcom_push(key='book_data', value=df.to_dict('records'))
    ^^
NameError: name 'ti' is not defined
[2024-09-26T16:19:25.923+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-26T16:19:25.923+0000] {logging_mixin.py:190} INFO - Task start:2024-09-26 16:19:14.668397+00:00 end:2024-09-26 16:19:25.922848+00:00 duration:11.254451
[2024-09-26T16:19:25.924+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Fetch_Books_Data> dag:<DAG: Amazon_Book_Data> dagrun:<DagRun Amazon_Book_Data @ 2024-06-25 00:00:00+00:00: scheduled__2024-06-25T00:00:00+00:00, state:running, queued_at: 2024-09-26 16:17:54.212291+00:00. externally triggered: False>
[2024-09-26T16:19:25.924+0000] {logging_mixin.py:190} INFO - Failure caused by name 'ti' is not defined
[2024-09-26T16:19:25.925+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Amazon_Book_Data, task_id=Fetch_Books_Data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240926T161914, end_date=20240926T161925
[2024-09-26T16:19:25.936+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-26T16:19:25.937+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task Fetch_Books_Data (name 'ti' is not defined; 1282)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/amazon_books.py", line 68, in fetch_books_data
    ti.xcom_push(key='book_data', value=df.to_dict('records'))
    ^^
NameError: name 'ti' is not defined
[2024-09-26T16:19:25.960+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-26T16:19:25.976+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-26T16:19:25.978+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-26T16:23:07.930+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-26T16:23:07.971+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Amazon_Book_Data.Fetch_Books_Data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-09-26T16:23:07.985+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Amazon_Book_Data.Fetch_Books_Data scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-09-26T16:23:07.987+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-26T16:23:08.018+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): Fetch_Books_Data> on 2024-06-25 00:00:00+00:00
[2024-09-26T16:23:08.043+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1364) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-26T16:23:08.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Amazon_Book_Data', 'Fetch_Books_Data', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/amazon_books.py', '--cfg-path', '/tmp/tmp3lrcao8i']
[2024-09-26T16:23:08.048+0000] {standard_task_runner.py:72} INFO - Started process 1392 to run task
[2024-09-26T16:23:08.049+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask Fetch_Books_Data
[2024-09-26T16:23:08.141+0000] {task_command.py:467} INFO - Running <TaskInstance: Amazon_Book_Data.Fetch_Books_Data scheduled__2024-06-25T00:00:00+00:00 [running]> on host f04706ee9217
[2024-09-26T16:23:08.325+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Amazon_Book_Data' AIRFLOW_CTX_TASK_ID='Fetch_Books_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-09-26T16:23:08.330+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-26T16:23:08.339+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-26T16:23:08.341+0000] {logging_mixin.py:190} INFO - Current task name:Fetch_Books_Data state:running start_date:2024-09-26 16:23:07.972811+00:00
[2024-09-26T16:23:08.342+0000] {logging_mixin.py:190} INFO - Dag name:Amazon_Book_Data and current dag run status:running
[2024-09-26T16:23:08.347+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-26T16:23:09.741+0000] {logging_mixin.py:190} INFO - Able to reach the site, scrapping data...
[2024-09-26T16:23:19.782+0000] {job.py:229} INFO - Heartbeat recovered after 11.97 seconds
[2024-09-26T16:23:20.909+0000] {logging_mixin.py:190} INFO - The webpage has been scrapped for data...
[2024-09-26T16:23:20.940+0000] {logging_mixin.py:190} INFO - Books data has been scrapped from the website succesfully !!!
[2024-09-26T16:23:21.139+0000] {logging_mixin.py:190} INFO - Number of books scrapped :  50
[2024-09-26T16:23:21.140+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/amazon_books.py", line 69, in fetch_books_data
    ti.xcom_push(key='book_data', value=df.to_dict('records'))
    ^^
NameError: name 'ti' is not defined
[2024-09-26T16:23:21.193+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-26T16:23:21.194+0000] {logging_mixin.py:190} INFO - Task start:2024-09-26 16:23:07.972811+00:00 end:2024-09-26 16:23:21.191568+00:00 duration:13.218757
[2024-09-26T16:23:21.195+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Fetch_Books_Data> dag:<DAG: Amazon_Book_Data> dagrun:<DagRun Amazon_Book_Data @ 2024-06-25 00:00:00+00:00: scheduled__2024-06-25T00:00:00+00:00, state:running, queued_at: 2024-09-26 16:23:03.230576+00:00. externally triggered: False>
[2024-09-26T16:23:21.196+0000] {logging_mixin.py:190} INFO - Failure caused by name 'ti' is not defined
[2024-09-26T16:23:21.196+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Amazon_Book_Data, task_id=Fetch_Books_Data, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240926T162307, end_date=20240926T162321
[2024-09-26T16:23:21.222+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-26T16:23:21.223+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task Fetch_Books_Data (name 'ti' is not defined; 1392)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/amazon_books.py", line 69, in fetch_books_data
    ti.xcom_push(key='book_data', value=df.to_dict('records'))
    ^^
NameError: name 'ti' is not defined
[2024-09-26T16:23:21.303+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-26T16:23:21.327+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-09-26T16:23:21.355+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-26T16:23:21.361+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
